# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b715e725da7061639a717d1a56109639cf6a621d49e6d98ebecb87ed5f77ab317045b667762441112fc8235f8fd85d63cc65d6ebbf4f5715843bed32ba950875

test:
  secret_key_base: 694dafdc802ea84f5bac593e895b3171ac05e2cfa599380fda3b4459e39fe8d9bed3a301390523c096c4f7518622a3ade15163c67576aeeaec5d48552068ad24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
